Make get_email() work with python3
If you try to build the docs with python3 you'll see something ending
with:
    ValueError: Couldn't find gerrit account with 'b'dmccowan@cisco.com''

This is because the default encoding from subprocess.Popen() under
python3 is bytes() which then fails to work with the gerrit API.

Check we have a text_type and decode() if needed.

Change-Id: Iccbc891a33d15ef82ddbc913549e64547a967195