Make the owners code work with python3
When generating electorate rolls under python3 we get the following:
 Traceback (most recent call last):
   File ".tox/venv/bin/generate-rolls", line 10, in <module>
     sys.exit(main())
   File "/home/tony/projects/openstack/openstack/election/openstack_election/cmds/generate_rolls.py", line 84, in main
     owners.main(options)
   File "/home/tony/projects/openstack/openstack/election/openstack_election/owners.py", line 532, in main
     normalized_project = normalize_project(project)
   File "/home/tony/projects/openstack/openstack/election/openstack_election/owners.py", line 60, in normalize_project
     return project.translate(maketrans(' -', '__')).lower()
 TypeError: a bytes-like object is required, not 'str'

Remove the python2 compat code and just use str.maketrans() always.

Change-Id: I12e351886d3e431144eeeb3a0efbd94dd0552946